3 create a dem from many laz tiles
rosepearson/GeoFabrics pull request #8
Opened 2021-07-13 21:50 UTC by rosepearson

Expand the pipeline to support many tiles from a single LiDAR dataset located on OpenTopography. Each tile is treated separately and added individually to the resulting dem.

2021-07-13 22:58 UTC, rosepearson commented
Work that still needs to be done as part of this PR:
* Add a linter to check spelling and formatting as part of the commit/pushing process using a hook
* Once finished with changes update the test benchmarks
*

2021-07-15 04:22 UTC, LukeParky requested changes
Good improvements in clarity included, and easy to follow structure of source code with the tiling additions

2021-07-15 21:06 UTC, rosepearson commented on src/geofabrics/processor.py
> +            self.instructions['instructions']['instructions'] else True
Yes - it's been bothering me too! I'll sort something out!

2021-07-15 23:49 UTC, rosepearson commented on src/geofabrics/processor.py
> +            self.instructions['instructions']['instructions'] else True
Great. Thanks @LukeParky - changes made.

2021-07-16 00:25 UTC, kinow commented on src/geofabrics/processor.py
> +        """ Return the file path from the instruction file. Raise an erro if not in the instructions. """
s/erro/error

2021-07-16 00:25 UTC, kinow commented on src/geofabrics/processor.py
> +        """ Return the resolution from the instruction file. Raise an erro if not in the instructions. """
s/erro/error

2021-07-16 01:55 UTC, rosepearson commented
Thanks for the review @LukeParky and @kinow. Let me know if there is anything else you'd like addressed.

2021-07-16 02:04 UTC, LukeParky approved these changes
The new changes to instructions are much more readable in the main body of the code. Looks good to pass PR

2021-07-16 02:37 UTC, merged